TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                templateRootPaths:
                  10: "EXT:form/Resources/Private/Frontend/Templates/"
                  201: "EXT:t3_sitepackage_onemorephoto/Resources/Private/Extensions/Cms/Form/Templates/"
                partialRootPaths:
                  10: "EXT:form/Resources/Private/Frontend/Partials/"
                  201: "EXT:t3_sitepackage_onemorephoto/Resources/Private/Extensions/Cms/Form/Partials/"
                layoutRootPaths:
                  10: "EXT:form/Resources/Private/Frontend/Layouts/"
                  201: "EXT:t3_sitepackage_onemorephoto/Resources/Private/Extensions/Cms/Form/Layouts/"
